repo: 'embed-containers'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-1
  - html
  - modulifier
  - modulifier-embed

html:
  - path: 'index.html'
    outline: false
    has:
      - 'link[href="css/modules.css"]'
      - 'div'

screenshots:
  - path: 'index.html'
    sizes: [320, 960]
